=== ankur4u007/skill_transform/xmlParser/src/main/java/xmlParser/xsds/dealprocessing.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="deals" type="deals" />
	
  <xs:complexType name="deals" >
	<xs:sequence>
      <xs:element name="deal" type="deal" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
   </xs:complexType>

  <xs:complexType name="deal">
    <xs:sequence>
      <xs:element name="id" type="xs:int" minOccurs="0"/>
      <xs:element name="descrption" type="xs:string" minOccurs="0"/>
      <xs:element name="startDate" type="xs:dateTime" minOccurs="0"/>
      <xs:element name="maturityDate" type="xs:dateTime" minOccurs="0"/>
      <xs:element name="facilityList" type="facility" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="facility">
    <xs:sequence>
      <xs:element name="amount" type="xs:double" minOccurs="0"/>
      <xs:element name="drawDownList" type="drawDown" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="id" type="xs:int" minOccurs="0"/>
      <xs:element name="maturityDate" type="xs:dateTime" minOccurs="0"/>
      <xs:element name="startDate" type="xs:dateTime" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="drawDown">
    <xs:sequence>
      <xs:element name="amount" type="xs:double" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="id" type="xs:int" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ankur4u007/skill_transform/xmlParser/src/main/java/xmlParser/xmls/dealprocessing.xml
<?xml version="1.0" encoding="UTF-8"?>
<deal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsds/dealprocessing.xsd">
  <id>0</id>
  <descrption>descrption</descrption>
  <startDate>2001-12-31T12:00:00</startDate>
  <maturityDate>2001-12-31T12:00:00</maturityDate>
  <facilityList>
    <amount>0.0</amount>
    <drawDownList/>
    <id>0</id>
    <maturityDate>2001-12-31T12:00:00</maturityDate>
    <startDate>2001-12-31T12:00:00</startDate>
  </facilityList>
</deal>
